---
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable         # enable new upcoming cops for rubocop
  Exclude:
    - _snippets/**/*
    - vendor/bundle/**/*
    - Rakefile
# Respect block length rules except for testing code
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile
    - app/controllers/app.rb
    - app/controllers/capsules.rb
    - app/controllers/accounts.rb

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - app/policies/*.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/controllers/app.rb

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/SymbolArray:
  Enabled: true
  Exclude:
    - app/db/migrations/*.rb
