---
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable         # enable new upcoming cops for rubocop
  Exclude:
    - _snippets/**/*

# Respect block length rules except for testing code
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - app/controllers/app.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/controllers/app.rb

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/SymbolArray:
  Enabled: true
  Exclude:
    # - Rakefile
    - app/db/migrations/*.rb