---
# COPY this file to secrets.yml

development:
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: pFrP9v4qQNRvpEeLl4RL0s8C3pmMyOKTYrjHhb2rq4g=
  DATABASE_URL: sqlite://app/db/store/development.db
  SIGNING_KEY: Y81DDN4V8U9jhSdr2wenyPxOnPZl/rOGcA9BgDa9b6M=
  VERIFY_KEY: Q8tj440HZo7cGHIQwqmr01wOpQVVLnNESydDwedhlmA=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  GOOGLE_ACCOUNT_URL: https://www.googleapis.com/oauth2/v1/userinfo?alt=json

test:
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: pFrP9v4qQNRvpEeLl4RL0s8C3pmMyOKTYrjHhb2rq4g=
  DATABASE_URL: sqlite://app/db/store/test.db
  SIGNING_KEY: Y81DDN4V8U9jhSdr2wenyPxOnPZl/rOGcA9BgDa9b6M=
  VERIFY_KEY: Q8tj440HZo7cGHIQwqmr01wOpQVVLnNESydDwedhlmA=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  GOOGLE_ACCOUNT_URL: https://www.googleapis.com/oauth2/v1/userinfo?alt=json

production:
  MSG_KEY: <`rake new_key:msg`>
  DB_KEY: <`rake new_key:db`>
  DATABASE_URL: <do not edit - allow production server to set>
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTPS
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  GOOGLE_ACCOUNT_URL: https://www.googleapis.com/oauth2/v1/userinfo?alt=json