---
# COPY this file to secrets.yml
development:
  MSG_KEY: Dyy1C75cr46fRl4db6vRz+79oMbHfR0K7/lHJij1q9Q=
  DB_KEY: hVJlSYvPTwgb8GiMyeaOK8pDIYPZ76FTrtEUZ2BPcs0=
  DATABASE_URL: sqlite://app/db/store/development.db
  SECURE_SCHEME: HTTP
  SENDGRID_FROM_EMAIL: jessica.huang+timecapsule@iss.nthu.edu.tw

test:
  MSG_KEY: Dyy1C75cr46fRl4db6vRz+79oMbHfR0K7/lHJij1q9Q=
  DB_KEY: hVJlSYvPTwgb8GiMyeaOK8pDIYPZ76FTrtEUZ2BPcs0=
  DATABASE_URL: sqlite://app/db/store/test.db
  SECURE_SCHEME: HTTP
  SENDGRID_FROM_EMAIL: jessica.huang+timecapsule@iss.nthu.edu.tw

production:
  MSG_KEY: <`rake new_key:msg`>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  DATABASE_URL: <set to production DB>
  SECURE_SCHEME: HTTPS
  SENDGRID_FROM_EMAIL: jessica.huang+timecapsule@iss.nthu.edu.tw